language: python
matrix:
  include:
    - python: "3.4"
      env: TOXENV=lint
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
install: "pip install -U tox coveralls"
script: tox
after_success: coveralls